const { readFileSync, createWriteStream, existsSync } = require('fs');
const axios = require('axios');

const abilityList = [
        {"name":"Aggression","cooldown":90,"icon":""},
        {"name":"Anticipation","cooldown":24.6,"icon":""},
        {"name":"Asphyxiate","cooldown":20.4,"icon":""},
        {"name":"Assault","cooldown":30,"icon":""},
        {"name":"Backhand","cooldown":15,"icon":""},
        {"name":"Balanced Strike","cooldown":120,"icon":""},
        {"name":"Barge","cooldown":20.4,"icon":""},
        {"name":"Barricade","cooldown":60,"icon":""},
        {"name":"Bash","cooldown":15,"icon":""},
        {"name":"Berserk","cooldown":60,"icon":""},
        {"name":"Binding Shot","cooldown":15,"icon":""},
        {"name":"Bladed Dive","cooldown":20.4,"icon":""},
        {"name":"Blood Tendrils","cooldown":45,"icon":""},
        {"name":"Bombardment","cooldown":30,"icon":""},
        {"name":"Cease (ability)","cooldown":0,"icon":""},
        {"name":"Chain","cooldown":10.2,"icon":""},
        {"name":"Cleave","cooldown":7.2,"icon":""},
        {"name":"Combust","cooldown":15,"icon":""},
        {"name":"Concentrated Blast","cooldown":5.4,"icon":""},
        {"name":"Corruption Blast","cooldown":15,"icon":""},
        {"name":"Corruption Shot","cooldown":15,"icon":""},
        {"name":"Dazing Shot","cooldown":5.4,"icon":""},
        {"name":"Deadshot","cooldown":30,"icon":""},
        {"name":"Death's Swiftness","cooldown":60,"icon":""},
        {"name":"Debilitate","cooldown":30,"icon":""},
        {"name":"Decimate","cooldown":7.2,"icon":""},
        {"name":"Deep Impact","cooldown":15,"icon":""},
        {"name":"Demon Slayer (ability)","cooldown":60,"icon":""},
        {"name":"Demoralise","cooldown":15,"icon":""},
        {"name":"Destroy","cooldown":20.4,"icon":""},
        {"name":"Detonate","cooldown":30,"icon":""},
        {"name":"Devotion","cooldown":60,"icon":""},
        {"name":"Dismember","cooldown":15,"icon":""},
        {"name":"Divert","cooldown":30,"icon":""},
        {"name":"Dragon Breath","cooldown":10.2,"icon":""},
        {"name":"Dragon Slayer (ability)","cooldown":60,"icon":""},
        {"name":"Eat Food","cooldown":0,"icon":""},
        {"name":"Escape","cooldown":20.4,"icon":""},
        {"name":"Essence of Finality","cooldown":0,"icon":""},
        {"name":"Flurry","cooldown":20.4,"icon":""},
        {"name":"Forceful Backhand","cooldown":15,"icon":""},
        {"name":"Fragmentation Shot","cooldown":15,"icon":""},
        {"name":"Freedom","cooldown":30,"icon":""},
        {"name":"Frenzy","cooldown":60,"icon":""},
        {"name":"Fury","cooldown":5.4,"icon":""},
        {"name":"Golden Touch","cooldown":120,"icon":""},
        {"name":"Greater Barge","cooldown":20.4,"icon":""},
        {"name":"Greater Chain","cooldown":10.2,"icon":""},
        {"name":"Greater Concentrated Blast","cooldown":5.4,"icon":""},
        {"name":"Greater Dazing Shot","cooldown":5.4,"icon":""},
        {"name":"Greater Flurry","cooldown":20.4,"icon":""},
        {"name":"Greater Fury","cooldown":5.4,"icon":""},
        {"name":"Greater Ricochet","cooldown":10.2,"icon":""},
        {"name":"Guthix's Blessing","cooldown":300,"icon":""},
        {"name":"Havoc","cooldown":10.2,"icon":""},
        {"name":"Horror","cooldown":15,"icon":""},
        {"name":"Hurricane","cooldown":20.4,"icon":""},
        {"name":"Ice Asylum","cooldown":300,"icon":""},
        {"name":"Immortality","cooldown":120,"icon":""},
        {"name":"Impact","cooldown":15,"icon":""},
        {"name":"Incendiary Shot","cooldown":60,"icon":""},
        {"name":"Incite","cooldown":0,"icon":""},
        {"name":"Ingenuity of the Humans","cooldown":90,"icon":""},
        {"name":"Kick","cooldown":15,"icon":""},
        {"name":"Kuradal's Favour","cooldown":60,"icon":""},
        {"name":"Limitless","cooldown":90,"icon":""},
        {"name":"Magma Tempest","cooldown":15,"icon":""},
        {"name":"Magma Tempest (Targeted)","cooldown":15,"icon":""},
        {"name":"Massacre","cooldown":60,"icon":""},
        {"name":"Metamorphosis","cooldown":60,"icon":""},
        {"name":"Meteor Strike","cooldown":60,"icon":""},
        {"name":"Natural Instinct","cooldown":120,"icon":""},
        {"name":"Needle Strike","cooldown":5.4,"icon":""},
        {"name":"Omnipower","cooldown":30,"icon":""},
        {"name":"Onslaught","cooldown":120,"icon":""},
        {"name":"Overpower","cooldown":30,"icon":""},
        {"name":"Piercing Shot","cooldown":3,"icon":""},
        {"name":"Preparation","cooldown":20.4,"icon":""},
        {"name":"Provoke","cooldown":10.2,"icon":""},
        {"name":"Pulverise","cooldown":60,"icon":""},
        {"name":"Punish","cooldown":3,"icon":""},
        {"name":"Quake","cooldown":20.4,"icon":""},
        {"name":"Quiver ammo slot 1","cooldown":0,"icon":""},
        {"name":"Quiver ammo slot 2","cooldown":0,"icon":""},
        {"name":"Rapid Fire","cooldown":20.4,"icon":""},
        {"name":"Reflect","cooldown":30,"icon":""},
        {"name":"Regenerate (ability)","cooldown":0,"icon":""},
        {"name":"Rejuvenate","cooldown":300,"icon":""},
        {"name":"Reprisal","cooldown":60,"icon":""},
        {"name":"Resonance","cooldown":30,"icon":""},
        {"name":"Revenge","cooldown":45,"icon":""},
        {"name":"Ricochet","cooldown":10.2,"icon":""},
        {"name":"Rout","cooldown":15,"icon":""},
        {"name":"Sacrifice","cooldown":30,"icon":""},
        {"name":"Salt the Wound","cooldown":15,"icon":""},
        {"name":"Sever","cooldown":15,"icon":""},
        {"name":"Shadow Tendrils","cooldown":45,"icon":""},
        {"name":"Shatter","cooldown":120,"icon":""},
        {"name":"Shock","cooldown":15,"icon":""},
        {"name":"Siphon","cooldown":60,"icon":""},
        {"name":"Slaughter","cooldown":30,"icon":""},
        {"name":"Slayer's Insight","cooldown":120,"icon":""},
        {"name":"Slice","cooldown":3,"icon":""},
        {"name":"Smash","cooldown":10,"icon":""},
        {"name":"Smoke Tendrils","cooldown":45,"icon":""},
        {"name":"Snap Shot","cooldown":20.4,"icon":""},
        {"name":"Snipe","cooldown":10.2,"icon":""},
        {"name":"Sonic Wave","cooldown":5.4,"icon":""},
        {"name":"Stomp (ability)","cooldown":15,"icon":""},
        {"name":"Storm Shards","cooldown":30,"icon":""},
        {"name":"Sunshine","cooldown":60,"icon":""},
        {"name":"Surge","cooldown":20.4,"icon":""},
        {"name":"Tight Bindings","cooldown":15,"icon":""},
        {"name":"Transfigure","cooldown":180,"icon":""},
        {"name":"Tsunami","cooldown":60,"icon":""},
        {"name":"Tuska's Wrath","cooldown":15,"icon":""},
        {"name":"Undead Slayer (ability)","cooldown":60,"icon":""},
        {"name":"Unload","cooldown":60,"icon":""},
        {"name":"Unsullied","cooldown":60,"icon":""},
        {"name":"Weapon Special attack","cooldown":0,"icon":""},
        {"name":"Wild Magic","cooldown":20.4,"icon":""},
        {"name":"Wrack","cooldown":3,"icon":""},
        {"name":"Wrack and Ruin","cooldown":3,"icon":""}
    ];


function rfc3986EncodeURIComponent (str) {
    let string2 = str.replace(/ /g, '_')
    return encodeURIComponent(string2).replace(/[!'()*]/g, escape);  
}
// rfc3986EncodeURIComponent(e.name)
abilityList.forEach(e => {
    console.log(`https://runescape.wiki/images/${rfc3986EncodeURIComponent(e.name)}.png`)
    axios({ url: `https://runescape.wiki/images/${rfc3986EncodeURIComponent(e.name)}.png`, responseType: 'stream' }).then(response =>
    new Promise((resolve, reject) => {
        response.data
            .pipe(createWriteStream('./images/' + e.name.replace(/ /g, '_') + '.png'))
            .on('finish', resolve)
            .on('error', reject)
    })
    )
})